name: 🚀 Deploy project to SFTP server

on:
  push:
    branches: [ main ]

jobs:
  sftp-deploy:
    name: 🧩 Deploying to SSH SFTP
    runs-on: ubuntu-latest

    steps:
      - name: 🔀 Checkout code from repository
        uses: actions/checkout@v4

      - name: 🛠 Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: 📦 Install dependencies
        run: npm install

      - name: 🧱 Build project
        run: npm run build

      - name: 📥 Install sshpass
        run: sudo apt-get install -y sshpass

      - name: 📤 Upload dist folder to remote SFTP server
        run: |
          sshpass -p "${{ secrets.SSH_PASSWORD }}" scp -o StrictHostKeyChecking=no -P ${{ secrets.SSH_PORT }} -r dist/* ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_IP }}:${{ secrets.SSH_PATH }}
